# Generated by Django 3.1.7 on 2021-02-28 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20210228_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_category', to='courses.category'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_levels', to='courses.level'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subcategory_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_subcategory', to='courses.category'),
        ),
    ]
